model: # Model specific parameters
  base_params:
    model_args: "pretrained=deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B,dtype=float16,max_model_length=768,gpu_memory_utilisation=0.7" # Model args that you would pass in the command line
  generation: # Generation specific parameters
#    max_new_tokens: 32768
    temperature: 0.6
    top_p: 0.95